import { Product } from "../types/product";

// Produits de secours au cas où la requête PHP échoue
export const fallbackProducts: Product[] = [
  {
    id: '1',
    name: 'Round 1.01ct H VS1 EX EX EX Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€1 916,43',
    specs: {
      clarity: 'VS1',
      color: 'H',
      cut: 'Excellent',
      dimensions: '6.51 × 3.97',
    },
  },
  {
    id: '2',
    name: 'Oval 1.50ct D IF EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€4 250,00',
    specs: {
      clarity: 'IF',
      color: 'D',
      cut: 'Excellent',
      dimensions: '7.21 × 4.15',
    },
  },
  {
    id: '3',
    name: 'Princess 2.01ct G VS2 VG VG Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€3 150,75',
    specs: {
      clarity: 'VS2',
      color: 'G',
      cut: 'Very Good',
      dimensions: '6.89 × 4.22',
    },
  },
  {
    id: '4',
    name: 'Pear 1.25ct E VVS1 EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€2 890,60',
    specs: {
      clarity: 'VVS1',
      color: 'E',
      cut: 'Excellent',
      dimensions: '7.02 × 4.11',
    },
  },
  {
    id: '5',
    name: 'Emerald 1.75ct F VS1 EX EX Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€3 475,90',
    specs: {
      clarity: 'VS1',
      color: 'F',
      cut: 'Excellent',
      dimensions: '7.15 × 4.08',
    },
  },
  {
    id: '6',
    name: 'Cushion 1.30ct I VVS2 VG EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€2 250,30',
    specs: {
      clarity: 'VVS2',
      color: 'I',
      cut: 'Very Good',
      dimensions: '6.75 × 4.01',
    },
  },
  {
    id: '7',
    name: 'Rond 0.90ct F VS2 EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€1 780,50',
    specs: {
      clarity: 'VS2',
      color: 'F',
      cut: 'Excellent',
      dimensions: '6.20 × 3.80',
    },
  },
  {
    id: '8',
    name: 'Marquise 1.15ct G VVS1 VG VG Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€2 340,75',
    specs: {
      clarity: 'VVS1',
      color: 'G',
      cut: 'Very Good',
      dimensions: '9.80 × 5.10',
    },
  },
  {
    id: '9',
    name: 'Oval 2.05ct D VS1 EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€5 120,90',
    specs: {
      clarity: 'VS1',
      color: 'D',
      cut: 'Excellent',
      dimensions: '10.20 × 7.30',
    },
  },
  {
    id: '10',
    name: 'Rond 1.50ct H SI1 VG EX Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€2 790,30',
    specs: {
      clarity: 'SI1',
      color: 'H',
      cut: 'Very Good',
      dimensions: '7.35 × 4.45',
    },
  },
  {
    id: '11',
    name: 'Princess 1.80ct F VS2 EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€3 980,25',
    specs: {
      clarity: 'VS2',
      color: 'F',
      cut: 'Excellent',
      dimensions: '7.00 × 7.00',
    },
  },
  {
    id: '12',
    name: 'Emerald 1.25ct E VVS2 VG VG Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€3 150,60',
    specs: {
      clarity: 'VVS2',
      color: 'E',
      cut: 'Very Good',
      dimensions: '7.90 × 5.80',
    },
  },
  {
    id: '13',
    name: 'Rond 2.00ct G VS1 EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€4 560,80',
    specs: {
      clarity: 'VS1',
      color: 'G',
      cut: 'Excellent',
      dimensions: '8.10 × 4.90',
    },
  },
  {
    id: '14',
    name: 'Pear 1.65ct D IF EX EX None',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€5 980,40',
    specs: {
      clarity: 'IF',
      color: 'D',
      cut: 'Excellent',
      dimensions: '11.20 × 6.90',
    },
  },
  {
    id: '15',
    name: 'Cushion 1.95ct F VVS1 EX EX Faint',
    image: '/placeholder.svg',
    image2: '/placeholder.svg',
    price: '€4 870,25',
    specs: {
      clarity: 'VVS1',
      color: 'F',
      cut: 'Excellent',
      dimensions: '8.30 × 6.70',
    },
  }
];
